dhamaniasad/awesome-postgres

README.md

Pomm is a PHP library on top of the PHP’s low level Postgres API. It provides on the fly type conversion offering a way to leverage SQL object oriented queries.

add Pomm to the list of language bindings

---

README.md

apgdiff (http://www.apgdiff.com/) is awesome and definitely deserves to be on this list. Saved me from hours of tedious manual comparison.

Adds apgdiff

---

README.md

DataGrip [https://www.jetbrains.com/datagrip/] is a really good commercial database IDE made by Jetbrains. The product is available on major platforms including Windows, Mac, and Linux. It is build on the IDEA platform which has a good reputation in Java community.

Add DataGrip to GUI list

---

README.md

Not sure how rejecting all of my previous adds makes any sense, but I'm trying again.

Added HA category and single item

---

README.md

Great series about why PostgreSQL is the better choice compared to
MySQL, MariaDB and Firebird.
closes dhamaniasad/awesome-postgres#71

Add article from compose.io explaining features of PostgreSQL

---

README.md

Adding item

---

README.md

Libzbxpgsql is a comprehensive PostgreSQL monitoring module for Zabbix
https://github.com/cavaliercoder/libzbxpgsql

Added libzbxpgsql

---

README.md

Add pgModeler, also sort the GUI list.

Add pgModeler

---

README.md

DBeaver is a fantastic opensource db manager, thought it ought to be in the list.
Thanks
Aym

Added DBeaver in GUI section

---

README.md

Add Wagon to GUI list

---

README.md

from his twitter account:
https://twitter.com/michaelpq/status/771534522277998593
https://twitter.com/michaelpq/status/771562101793972225

fix Paquier's blog link

---

README.md

Some sections were sorted, but others were in more or less random order.  This PR sorts all sections alphabetically, but maintains the Planet PostgreSQL link as the first in blog list.

Sort the lists alphabetically

---

README.md

@dhamaniasad As a disclaimer, I'm currently working on Citus, but thought it might still be helpful to have in the list.

Add Citus to Server section

---

README.md

check_pgactivity provide several services to monitor Postgres.

Add check_pgactivity

---

README.md

Hi there!
I'm adding reference to pgconfig.org.
pgconfig.org it's another tuning suggestion tool, also based in pgtune, but with a few more features.
Thanks for this awesome list!

adding reference to pgconfig.org

---

README.md

Trying to get one step closer to getting [PR-808](https://github.com/sindresorhus/awesome/pull/808) merged.

Attempt to normalize naming across the board.

---

README.md

Update Planet PostgreSQL

---

README.md

pg_probackup is actively developed and seems to be promising, with great features, adding it to the list

pg_probackup added

---

README.md

pgbench — run a benchmark test on PostgreSQL

added pgbench to PostgreSQL Monitoring Section

---

README.md

pg-promise is a mature, well tested postgres binding for nodejs with promise interface.

Add pg-promise

---

.travis.yml
README.md

based on https://github.com/sindresorhus/awesome/pull/808#issuecomment-258089249
and https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md
I hope - this is resolving 2 strict points: 
* Include project logo in the top right,  .. ( based on [suggested example](https://github.com/sindresorhus/awesome-electron) )
* summary at the top about PostgreSQL ...  ( based on [suggested example](https://github.com/woop/awesome-quantified-self) )

add project logo and a summary

---

README.md

Add:
* [Amazon RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/) - Amazon Relational Database Service (RDS) for PostgreSQL

add: Amazon RDS for PostgreSQL

---

README.md

Out of interest, Holistics wrote an article that was featured on Postgres Weekly, on why PostgreSQL trumps MySQL for data warehousing and reporting. There's a link to the article on their site blog https://www.holistics.io/

Add Holistics to GUI

---

README.md

I just read the contributing guideline, sorry this pull request is more than one item. They are pretty simple changes.
*  Added pgMemento
*  Updated the link to pgTune and pgConfig - their website seem to be down, so I linked to what seems to be their github projects directly.

add pgMemento, updated links for pgTune and pgConfig

---

README.md

Did I choose right categories?

Add timescale and pipeline db

---

README.md

Add  pg_bulkload  http://ossc-db.github.io/pg_bulkload/index.html

Add  pg_bulkload - It's a high speed data loading utility for Postgres

---

README.md

Add opm.io

---

README.md

Well tested and Valgrind analyzed.
Thank you!

add pg_migrate

---

README.md

Adds PostGraphQL, A GraphQL schema created by reflection over a PostgreSQL schema, in Utilities list

Added PostGraphQL for PostgreSQL in Utilities list

---

README.md

Add Valentina Studio

---

README.md

Add binding for Lua

---

README.md

Add postgresDBSamples

---

README.md

OmniDB is a browser-based tool that simplifies database management focusing on interactivity, designed to be powerful and lightweight.

Added OmniDB to GUI section

---

README.md

* add pg_web_stats to optimizations category

add pg_web_stats to optimizations category

---

README.md

Hi,
I'm maintaining ldap2pg, a feature full utility to create/alter/drop roles and grant/revoke privileges with LDAP synchronisation ability.
What do you think of this ?
Regards,
Étienne

Add ldap2pg utility

---

README.md

According to https://github.com/dalibo/pgbadger has been moved to
https://github.com/darold/pgbadger

Update pgbadger link

---

README.md

Once I saw it I couldn't leave it be :)

Fix spelling of channel

---

README.md

ref: https://www.pipelinedb.com/
> An open-source PostgreSQL extension that runs SQL queries continuously on streams, incrementally storing results in tables.

fix wrong definition of PipelineDB

---

README.md

I discover this project (which is actually quite old, and still maintained) which could be of interest for people willing to do big data with PostgreSQL. (I'm not link to the project in any way.)

Add Greenplum Database

---

README.md

Added DigitlOcens new offering.

Added DigitalOcean Managed Databases

---

README.md

Postgres/PostGIS extension for path finding in the database.

Add pgRouting

---

README.md

Add Haskell bindings

---

README.md

Add useful scripts by Data Egret team

---

README.md

The link returns a cloudflare error which is breaking travis for all other PRs. 
@zaiste please ping when the site is fixed and will be happy to add the post back.

Remove PG Primer blog post

---

README.md

Pogi is a wrapper around node-postgres, with advanced capabilities. A stable library that we use in production, definitely worth mentioning.

Add "pogi"

---

README.md

Reverts dhamaniasad/awesome-postgres#256

Revert "Remove PG Primer blog post"

---

README.md

Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244

Rename Timescale to TimescaleDB

---

README.md

Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244

Add Nancy CLI by Postgres.ai team

---

README.md

Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244/files

Add postgres-checkup by Postgres.ai team

---

README.md

Add a link in Videos to: https://www.scalingpostgres.com/

add scaling postgres to videos

---

README.md

Instant realtime GraphQL APIs on any Postgres application, existing or new.

Add : Utilities : Hasura

---

README.md

We have implemented a lot in WAL-G since this line was initially added :)

Update WAL-G info

---

README.md

Node.js module for easy synchronization of postgres tables with models (json-schemas).
Migration alternative.
Tested on a real projects.
Thanks!

add pg-differ to the Utilities section

---

README.md

https://github.com/porsager/postgres

Add postgres node.js binding

---

README.md

Separate changes from https://github.com/dhamaniasad/awesome-postgres/pull/244
Issue #236

Add TimescaleDB Tune to optimization section

---

README.md

Hello! I'm the maintainer of [pgsh](https://github.com/sastraxi/pgsh) and would love to get the word out about the tool we're building. Let me know if you have any questions!

Add pgsh to the CLI section

---

README.md

We added support for PostgreSQL in September 2018 in release 1.14
https://www.percona.com/doc/percona-monitoring-and-management/release-notes/1.14.0.html

Adding PMM from Percona

---

README.md

[pgmetrics](https://pgmetrics.io/)
On GitHub: https://github.com/rapidloop/pgmetrics

Add pgmetrics monitoring tool

---

README.md

[pg_flame](https://github.com/mgartner/pg_flame) turns `EXPLAIN ANALYZE` output into [flamegraphs](http://www.brendangregg.com/flamegraphs.html). These visualizations help to understand the hierarchy and relative time of each step in the plan. Use pg_flame to debug slow queries.

Add pg_flame

---

README.md

Hasura and graphql-engine are same

remove duplicate entry under utilities

---

README.md

Generate fullstack PostgreSQL apps with Angular, Vue or React.

Add ScaffoldHub

---

README.md

Google Cloud SQL PostgreSQL isn't Beta.

Minor change to Google's PostgreSQL description

---

README.md

This used to be alphabetized. I fixed it, and added a new FOSS gui client.

Re-alphabetized and added Beekeeper Studio

---

README.md

Chartbrew is an open-source platform that can be self-hosted or subscribed to. Works with PostgreSQL among other data sources.
Here's the repo: https://github.com/chartbrew/chartbrew

Added Chartbrew to the list of GUI software

---

README.md

Adding YugabyteDB  with the forks of PostgreSQL

Add YugabyteDB in the list of Servers

---

README.md

Atlas is a tool for managing and migrating database schemas using modern DevOps principles.

doc: add Atlas CLI

---

README.md

This PR adds [Neon](https://neon.tech) to the list of PaaS

Add Neon to the list of PaaS

---

README.md

Hi,
Stjepan from Manning here. As we have released a new MEAP for "PostgreSQL Mistakes and How to Avoid Them" by Jimmy Angelakos, I've added the "Books" section so that I can link the book in my next PR. Thank you for considering it.
Best,

Added "Books" section to resources

---

README.md

Hi,
Stjepan from Manning here. As announced, I've added our latest MEAP release "PostgreSQL Mistakes and How to Avoid Them" by Jimmy Angelakos, in addition to my previous PR for adding the "Books" section. Please let me know if this works. Thank you for considering it.
Best,

Added PostgreSQL Mistakes and How to Avoid Them

---

README.md

Adding Metis application to the optimization section.
Adding Metis blog to the blogs section.

Add Metis application and Metis blog

---

README.md

fixes https://github.com/dhamaniasad/awesome-postgres/issues/347

feat: adds Supabase as PaaS

---

README.md

Hi!
This PR adds ParadeDB and its two main extensions, which can also be used independently of ParadeDB itself. Thank you for maintaining this repository and for including us!

Add ParadeDB and its extensions

---

README.md

Add new entries to `awesome-postgres`
* [Pigsty](https://github.com/Vonng/pigsty) - Battery-Included Open-Source Distribution for PostgreSQL with ultimate observability & Database-as-Code toolbox for developers.
* [pg_exporter](https://github.com/Vonng/pg_exporter) - Fully customizable Prometheus exporter for PostgreSQL & Pgbouncer with fine-grained execution control.

add pigsty to distributions & pg_exporter to monitoring

---

README.md

Adds [pgMagic](https://pgmagic.app) to readme - a pg GUI client I developed that lets you talk in natural language to postgres and have generated SQL execute immediately.
Let me know if you would like a license to test it out :)

Add pgMagic to readme

---

README.md

add pg_auto_failover in High-Availability section

add pg_auto_failover in High-Availability section

---

README.md

Teable is a no-code database built on Postgres. Let non-tech people use the database to build applications

Add Teable

---

README.md

Sorry that this violates the single link per request - I just wanted to show that there were a few potentially worth including

Add a podcasts section

---

README.md

Provides utilities for Postgres database schema versioning.

Adding link to Pyrseas

---

README.md

adding planter entry - Generate PlantUML ER diagram textual description from PostgreSQL tables

adding planter entry - Generate PlantUML ER diagram textual description from PostgreSQL tables

---

README.md

pg_timetable extension was added, useful for scheduling tasks.

pg_timetable extension - schedule tasks

---

README.md

Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>

Blogs: Added Percona's PostgreSQL blog posts

---

README.md

Adds Datadog to the Monitoring section.

Add Datadog to Monitoring section

---

README.md

Adds Coroot to Monitoring section

Add Coroot to Monitoring section

---

README.md

Update `README.md`  to add OrioleDB to the Extensions section.

Add OrioleDB

---

README.md

DbVisualizer is a desktop SQL client that's been around for many years and works great with PostgreSQL. https://www.dbvis.com

Add DbVisualizer to the list of GUIs

---

README.md

Add Autobase for PostgreSQL

---

README.md

The [RegreSQL](https://github.com/dimitri/regresql) tool implement a regression testing facility for SQL queries, and supports the PostgreSQL database system. A regression test allows to ensure known results when the code is edited.
This tool is inspired by the PostgreSQL regression testing framework. It's been written in the process of the [Mastering PostgreSQL](http://masteringpostgresql.com/) book as an example of an SQL framework for unit testing and regression testing.

Add RegreSQL to Utilities
