dhamaniasad/awesome-postgres

README.md

This is the library used by pgloader.

Add link to Postmodern Common Lisp library.

---

README.md

[Database Labs](https://www.databaselabs.io) - Get a production-ready cloud Postgres server in minutes, from $20 a month. Backups, monitoring, patches, and 24/7 tech support all included.

Add Database Labs -- Postgres as a Service

---

README.md

I hope this is not too much of a shameless self plug. But I think this is a missing tool in the PostgreSQL ecosystem.

Add pgclimb export tool

---

README.md

Wagon is shutting down. See the transition faq: https://www.wagonhq.com/faq

Remove Wagon as it is shutting down.

---

README.md

OS X will soon be known as macOS. The [Awesome macOS](https://github.com/iCHAIT/awesome-macOS) list already reflects this.

Rename OS X and Mac to macOS.

---

README.md

This change adds Citus Cloud, which offers a scaled-out and fully managed PostgreSQL cluster, to Paas list.

Add Citus extension and Citus Cloud Paas, remove deprecated pg_shard

---

README.md

Added `Cyan Audit` for DML logging tool for `PostgreSQL` in `PG Extenstion` list

CyanAudit added to list of PG Extenstions

---

README.md

A lightweight Postgres LISTEN Daemon built on top of [node](https://nodejs.org/en/), [node-postgres](https://github.com/brianc/node-postgres) and [systemd](https://wiki.debian.org/systemd).
It's a very simple yet generic daemon application that could be used in any project that makes use of Postgres' `LISTEN`/`NOTIFY` feature.
It runs as a background process that does `LISTEN` on the configured channels on a database(s) and allows to perform custom actions on receiving [`NOTIFY`](https://www.postgresql.org/docs/9.1/static/sql-notify.html) signals on those channels.
Find more information here in the [README](https://github.com/kabirbaidhya/pglistend).

Add pglistend in the Utilities section

---

README.md

Add link to [PAF](https://github.com/dalibo/PAF): PostgreSQL Automatic Failover: High-Availibility for Postgres, based on Pacemaker and Corosync. Closes #150.

README: High-Availability: Add link to PAF

---

README.md

I would like to add pREST Tool .
* [pREST](https://github.com/nuveo/prest) - Serve a RESTful API from any PostgreSQL database (Golang) 
imho : sometimes it is also important the implementation language - so I added this information :  `(Golang)`

add pREST ( Serve a RESTful API from any PostgreSQL database )

---

README.md

my proposal:  New category:  **"Docker images"**
* [citusdata/citus](https://hub.docker.com/r/citusdata/citus/) - Citus official images with citus extensions. Based on the official Postgres container.
* [mdillon/postgis](https://hub.docker.com/r/mdillon/postgis/) - PostGIS 2.3 on Postgres 9. Based on the official Postgres container.
* [postgres](https://hub.docker.com/_/postgres/) -  Official postgres container (from Docker)

proposing new category : "docker images"

---

README.md

pgwatch2 is a flexible Docker-first Postgres monitoring-in-a-box solution that enables getting up and running very fast.

Added "pgwatch2" to Monitoring section

---

README.md

The link for pgModerler points to a https domain with an invalid certificate that then redirects to the new URL for pgModeler, so **I just put the final secure URL** to avoid the redirection and the certificate warnings:

Fixed pgModeler URL

---

README.md

(To authenticate this, you can visit the old GitHub repo URL and notice it redirects to the new one; more info at https://www.graphile.org/history/)
🙏

Rename PostGraphQL to PostGraphile

---

README.md

Pg_chameleon is a tool which setup a real time replica from MySQL to PostgreSQL with optional type override migration and migration capabilities.
The tool is released under the terms of the 2-clause BSD license.
Thanks

add pgchameleon to the utilities list

---

README.md

[pg_insights](https://github.com/lob/pg_insights) is a collection of SQL commands for monitoring Postgres health. It has been battle-tested in production environments at [Lob](https://lob.com), helping us pinpoint Postgres issues. It is inspired by the excellent [pg_extras](https://github.com/heroku/heroku-pg-extras) tool.

Add pg_insights

---

README.md

There multiple PostgreSQL drivers, but most of them are based on the interface provided by psycopg2. asyncpg besides being asyncio compatible driver it also did not followed to be compatible with Python's DB-API and instead provided interface that directly matches PostgreSQL API. The disadvantage to it is that it probably won't work with other ORM libraries, but in exchange for it it is extremely fast and much better alternative if you want to utilize PostgreSQL latest features in your code.

Added asyncpg to python

---

README.md

[pg_docs_bot](https://github.com/mchristofides/pg_docs_bot) is a little browser extension that I made and have been happily using for a couple of weeks.
All it does is:
- Redirects docs links to the "current" version
- After redirecting, displays a notice (including a link to the page you were redirected from)
- Avoids redirecting some deprecated features (to avoid 404s)
- Avoids redirecting when coming from another page in the docs, so you can still check old versions (the main problem with generic redirectors)
It's super simple, and a few others are using it too now, but no worries if it's not quite right for this list!

Add pg_docs_bot

---

README.md

Hi Asad,
I came across your repository [awesome-postgres](https://github.com/dhamaniasad/awesome-postgres) and found it to be a valuable resource for PostgreSQL enthusiasts.
While browsing through the repository, I noticed that it was missing links to any structured guides such as the famous ["PostgreSQL Roadmap"](https://roadmap.sh/postgresql-dba). I took the initiative to submit a ["Pull Request"](https://github.com/dhamaniasad/awesome-postgres/pull/343) adding it in a under resources section.
Thank you for your time and effort in maintaining this valuable resource :)
Best,
Mouaaz

Added link of PostgreSQL Roadmap

---

README.md

[pgx](https://github.com/tcdi/pgx) is a framework for developing PostgreSQL extensions in Rust and strives to be as idiomatic and safe as possible. pgx supports Postgres v11-v15.

Add Rust binding pgx

---

README.md

A PR was recently merged to add ParadeDB and its Postgres extensions, pg_search and pg_analytics, to this awesome list. This PR adds our latest and final extension, pg_lakehouse.

Add pg_lakehouse

---

README.md

[pgPedia](https://pgpedia.info/) - An encyclopedia of things related to postgreSQL.

docs: add pgPedia resource

---

README.md

[wtx](https://github.com/c410-f3r/wtx) is written in Rust and provides "bindings" to PostgreSQL databases. It is one of the fastest, if not the fastest, implementation according to https://github.com/diesel-rs/metrics as well as internal benchmarks.

Add new `wtx` client

---

README.md

This PR adds FerretDB – a truly Open Source MongoDB alternative on top of PostgreSQL.
(full disclosure: I'm a FerretDB author, but that's not the only reason I think it is awesome)

Add FerretDB

---

README.md

Very interesting service provider IMHO, this is one of the main reason I looked into it:
```
ScaleGrid is the only DBaaS that lets you host in your own cloud account and
save with AWS or Azure Reserved Instances or GCP Committed Use Discount.
```

Adding ScaleGrid DBaaS

---

README.md

[pg_stat_monitor](https://github.com/percona/pg_stat_monitor) provides improved insights that allow database users to understand query origins, execution, planning statistics and details, query information, and metadata.
This significantly improves observability, enabling users to debug and tune query performance. pg_stat_monitor is developed on the basis of pg_stat_statements as its more advanced replacement.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>

Extensions: Added pg_stat_monitor

---

README.md

Added Security category, add Acra.
[Acra](https://github.com/cossacklabs/acra) is a database security proxy that helps developer to encrypt data before storing in the database ("transparent field level encryption").

Add category Security, and Acra into it

---

README.md

Noticed 2 links are no longer maintained.
Links removed for cleanup: omnidb & dbglass.

Remove deprecated links: omnidb, dbglass

---

README.md

The Vert.x PostgreSQL client is an asynchronous and high performance client for Java, the project is also listed here https://vertx.io/docs/vertx-pg-client/java/ (disclaimer I am one of the contributor of the project).

Add the Vert.x PostgresSQL client to the list of Java clients

---

README.md

GatewayD is a free and open-source cloud-native database gateway and framework for building data-driven applications. It is a middleware that sits between your database servers and clients and proxies all their communication. It is like API gateways in system design, but instead is used for proxying database traffic, rather than HTTP traffic.

Add GatewayD

---

README.md

A daemon to run stateful Postgres on cheap AWS Spot VMs

Add pg-spot-operator

---

README.md

Looks like pg_analytics is it's own repo now:
https://github.com/paradedb/pg_analytics

pg_analytics updated URL

---

README.md

Adds a link to the [{RPostgres}](https://github.com/r-dbi/RPostgres) package, a DBI-compliant R library that serves as a modern alternative to [{RPostgreSQL}](https://github.com/tomoakin/RPostgreSQL).

Add `{RPostgres}` link to README.md

---

README.md

Add NServiceBus.Transport.PostgreSQL, which allows PostgreSQL to be used as a message broker.

Add NServiceBus.Transport.PostgreSQL as a Commercial Utility

---

README.md

BeanQueue is a lightweight Python task queue framework based on [SQLAlchemy](https://www.sqlalchemy.org/), PostgreSQL [SKIP LOCKED queries](https://www.2ndquadrant.com/en/blog/what-is-select-skip-locked-for-in-postgresql-9-5/) and [NOTIFY](https://www.postgresql.org/docs/current/sql-notify.html) / [LISTEN](https://www.postgresql.org/docs/current/sql-listen.html) statements. It makes queue background task with database transaction easier than ever. The tasks can be created like any other ORM objects, added to session and committed altogether with other table rows.
We built this project internally for our own use, and we use it in production already. We think it could be helpful for others, so we open sourced it.
There are actually many PostgreSQL based worker queue system out there. …

Add BeanQueue
